In [1]:
#### 1. Convert the given list into a numpy array and replace the odd elements with -2.
#### Lst =[[1,2,3],
#### [4,5,6],
#### [7,8,9]]

import numpy as np

arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
    
for i in range(len(arr)):
    if (i%2==0):
        arr[i] = -2
print(arr)

[[-2 -2 -2]
 [ 4  5  6]
 [-2 -2 -2]]


In [2]:
#### 1. Convert the given list into a numpy array and replace the odd elements with -2.
#### Lst =[[1,2,3],
#### [4,5,6],
#### [7,8,9]]

import numpy as np

arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
    
arr[arr%2==1] = -2
print(arr)

[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [3]:
#### 2. In the numpy array given below print all the elements ranging from 8 to 15.
####     arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]

import numpy as np

arr = np.array([1,2,3,4,5,8,9,10,12,22,32,54,99,6,7])

for i in range(len(arr)):
    if arr[i] >= 8 and arr[i] <=15:
        print(arr[i])

8
9
10
12


In [4]:
#### 3. Create a 3*3 narray that includes numbers from 1 to 9 and swap columns 1 and 2.

import numpy as np

v = np.arange(1,10).reshape(3,3)
print('Before Swap:\n', v)

#Syntax -> arr[:, [start_index, last_index]] = arr[:, [last_index, start_index]]

v[:,[1,0]] = v[:,[0,1]]
print('After Swap:\n', v)

Before Swap:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Swap:
 [[2 1 3]
 [5 4 6]
 [8 7 9]]


In [5]:
#### 4. In the given numpy array replace the NaN values with the average of columns
####    arr = np.array([[1.3, 2.5, 3.6, np.nan],
####                    [2.6, 3.3, np.nan, 5.5],
####                    [2.1, 3.2, 5.4, 6.5]])


import numpy as np

# Initialising numpy array
ini_array = np.array([[1.3, 2.5, 3.6, np.nan],
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])

# printing initial array
print ("initial array", ini_array)

# column mean
col_mean = np.nanmean(ini_array, axis = 0)

# printing column mean
print ("columns mean", str(col_mean))

# find indices where nan value is present
inds = np.where(np.isnan(ini_array))

# replace inds with avg of column
ini_array[inds] = np.take(col_mean, inds[1])

# printing final array
print ("final array", ini_array)

initial array [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
columns mean [2.  3.  4.5 6. ]
final array [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [9]:
#### 5. For the numpy array given below perform the following operation:
#### i.Convert the numpy array into a numpy matrix
#### ii.Sort the values in a matrix
#### arr = [[2,4,6],
####       [1,3,5]]

import numpy as np

arr = np.array([(2,4,6),(1,3,5)])
arr1 = arr.ravel()
arr1 = np.sort(arr1)
print(arr1)

[1 2 3 4 5 6]
