5. How do you count the frequency of each value appearing in the given array of integers?

[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

Answer: 
array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1]) 
which means 0 comes 4 times, 1 comes 2 times, 2 comes 1 time, 3 comes 1 time and so on.

In [ ]:
arr =  [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

arr_count = []
for item in np.arange(0,10):
    if np.isin(item,arr):
        arr_count.append(arr.count(item))
    else:
        arr_count.append(0)
print(arr_count)

6. Create a NumPy array [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) and filter the elements greater than 5.

In [65]:
import numpy as np

arr = np.array( [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]])
print("Elements greater than 5:", arr[arr>5])

Elements greater than 5: [ 6  7  8  9 10 11]


7. Create a NumPy array having NaN (Not a Number) and print it.

array([ nan, 1., 2., NaN, 3., 4., 5.])

Print the same array omitting all elements, which are NaN.

In [71]:
ex7 = np.array([np.nan, 1., 2., np.NaN, 3., 4., 5.])
print(ex7)
print(ex7[~np.isnan(ex7)])

[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


8. Create a 10x10 array with random values and find the minimum and maximum values.

In [112]:
ex8 = np.random.randint(99,size=(10,10))

print("Shape of the array:", ex8.shape)

print("\n",ex8)

print(f"\nMin value:{ex8.min()}, Max Value: {ex8.max()}")

Shape of the array: (10, 10)

 [[51 42 47 51 78 27 67 90 94 12]
 [24 67 49  6 69 64 13 96 38 10]
 [91 39 61 98 15 32 27  9 13 31]
 [51 62 77 75 81 88 82  2 31  9]
 [59  3 86 82 19 18 33 55 81 97]
 [77 36 24 47 71 47 23 93 24  5]
 [24 42 26 77 46 41 26 25 88 67]
 [28 90 44 16 37 91 31 19 14  2]
 [44 78 67 34 82 85  4 89 42 97]
 [35 29 33 24 12 43 26 22 26 76]]

Min value:2, Max Value: 98


9. Create a random vector of size 30 and find the mean value.

In [140]:
# random.random_integers(low, high=None, size=None) -> Will generate 30 random numbers between 0-10

ex9 = np.random.rand(30)
print(ex9)
print("\nMean is:",ex9.mean())

[0.12739517 0.04283945 0.03928758 0.37969258 0.07353353 0.87471345
 0.22355967 0.95339502 0.26030868 0.93919346 0.67276944 0.25440801
 0.10015855 0.7180105  0.39301165 0.03903159 0.73153595 0.91197005
 0.36926297 0.98713587 0.58771228 0.88679564 0.19649179 0.44747425
 0.39426272 0.6764841  0.38594156 0.06262035 0.85084888 0.51943985]

Mean is: 0.4699761531836609


10. Create a NumPy array having elements 0 to 10 And negate all the elements between 3 and 9.

In [184]:
ex10 = np.random.randint(20,size=(3,5))
print("Original List:\n",ex10)
print("Modified List:")
print(np.where((ex10 > 2) & (ex10 < 10),ex10*-1, ex10))

Original List:
 [[ 7 11 11  3  8]
 [11  6 18 18 13]
 [ 4  4  0  1  8]]
Modified List:
[[-7 11 11 -3 -8]
 [11 -6 18 18 13]
 [-4 -4  0  1 -8]]
